In [ ]:
import torch

In [ ]:
print(torch.__version__)

1.7.0+cu101


In [ ]:
a = torch.tensor([1, 2, 3])
print(a)
print(type(a))
print(a.dim())
#a.shape
print(type(a[0]))
print(type(a[0].item()))

tensor([1, 2, 3])
<class 'torch.Tensor'>
1
<class 'torch.Tensor'>
<class 'int'>


In [ ]:
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(b)
print(type(b))
print(b.dim())
print(b.shape)
print(b[0, 1])
print(b[1, 2])
b[0, 2] = 10
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])
<class 'torch.Tensor'>
2
torch.Size([2, 3])
tensor(2)
tensor(6)
tensor([[ 1,  2, 10],
        [ 4,  5,  6]])


In [ ]:
c = None
################################################################################
# TODO: Construct a tensor c filled with all zeros, initializing from nested   #
# Python lists.                                                                #
################################################################################
c = torch.tensor([[0, 0], [0, 0], [0, 0]])
################################################################################
#                              END OF YOUR CODE                                #
################################################################################
print('c is a tensor: ', torch.is_tensor(c))
print('Correct shape: ', c.shape == (3, 2))
print('All zeros: ', (c == 0).all().item() == 1)

################################################################################
# TODO: Set element (0, 1) of c to 10, and element (1, 0) of c to 100.         #
################################################################################
c[0, 1] = 10
c[1, 0] = 100
################################################################################
#                              END OF YOUR CODE                                #
################################################################################
print('\nAfter mutating:')
print('Correct shape: ', c.shape == (3, 2))
print('c[0, 1] correct: ', c[0, 1] == 10)
print('c[1, 0] correct: ', c[1, 0] == 100)
print('Rest of c is still zero: ', (c == 0).sum().item() == 4)

c is a tensor:  True
Correct shape:  True
All zeros:  True

After mutating:
Correct shape:  True
c[0, 1] correct:  tensor(True)
c[1, 0] correct:  tensor(True)
Rest of c is still zero:  True


In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2, 1:3]
print(b)
print(type(a))
print(a.shape)
#a = np.zeros((2,3))
print(a)
b = np.ones((1,2))
print(b)
c = np.full((2,3), 7)
print(c)
d = np.eye(3)
print(d)
e = np.random.random((2,3))
print(e)
row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r1[0] = 10
print(a)
print(row_r1)
print(row_r2)
print(row_r1.shape)
print(a[[0, 1, 2], [0, 1, 2]])
b = a[[0, 1, 2], [0, 1, 2]]
print(b.shape)
b[0] = 9
print(a)
a = np.array([[1,2], [3,4], [5,6]])
bool_idx = (a>3)
print(bool_idx)
print(a[a<4])
x = np.array([1, 2])
print(x.dtype)
x = np.array([1.0, 2.0])
print(x.dtype)
print(x)
x = np.array([1, 2.0], dtype=np.int64)
print(x.dtype)
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.int64)
print(x+y)
print(np.add(x, y))
print(np.sqrt(y))

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
print(x*y)
print(v.dot(w))
print(np.dot(v, w))
print(x.dot(v))
print(x.T)
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x)
print(y)
for i in range(4):
    y[i, :] = x[i, :] + v
vv = np.tile(v, (4,2))
v = np.array([1,2,3])
w = np.array([4,5])
print(np.reshape(v, (3, 1))*w)
x = np.array([[1,2],[3,4]])
print((x.T + w).T)
print(x + np.reshape(w, (2,1)))

In [ ]:
!pip uninstall scipy

In [ ]:
!pip install scipy==1.1.0

In [ ]:
import numpy as np
from scipy.misc import imread, imsave, imresize

img = imread('assets/cat.jpg')
print(img.dtype, img,shape)
img_tinted = img * [1, 0.95, 0.9]
img_tinted = imresize(img_tinted, (300,300))
imsave('assets/cat_tinted.jpg', img_tinted)

In [ ]:
!pip install Pillow

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 3*np.pi, 0.1)
print(x)
y_sin = np.sin(x)
y_cos = np.cos(x)
plt.subplot(2,1,1)
plt.plot(x, y_sin)
plt.title('sine')
plt.subplot(2,1,2)
plt.plot(x, y_cos)
plt.title('cosine')
plt.show()


In [ ]:
!cat /etc/issue.net

Ubuntu 18.04.5 LTS


In [ ]:
!df -h

In [ ]:
!nvidia-smi

In [ ]:
import torch
a = torch.zeros(2,3)
print(a)
b = torch.ones(1,2)
print(b)
c = torch.eye(3)
print(c)
d = torch.rand(4,5)
print(d)

In [ ]:
e = None
################################################################################
# TODO: Create a tensor of shape (2, 3, 4) filled entirely with 7, stored in e #
################################################################################
# Replace "pass" statement with your code
e = torch.ones(2,3,4)
e = e*7
################################################################################
#                              END OF YOUR CODE                                #
################################################################################
print('e is a tensor:', torch.is_tensor(e))
print('e has correct shape: ', e.shape == (2, 3, 4))
print('e is filled with sevens: ', (e == 7).all().item() == 1)

e is a tensor: True
e has correct shape:  True
e is filled with sevens:  True


In [ ]:
x0 =  torch.tensor([1, 2])
x1 = torch.tensor([1., 2])
x2 = torch.tensor([1., 2])
print(x0.dtype)
print(x1.dtype)
print(x2.dtype)

torch.int64
torch.float32
torch.float32


In [ ]:
y0 = torch.tensor([1,2], dtype=torch.float32)
y1 = torch.tensor([1,2], dtype=torch.int32)
y2 = torch.tensor([1,2], dtype=torch.int64)
print(y0.dtype)
print(y1.dtype)
print(y2.dtype)
z0 = torch.ones(1,2)
z1 = torch.ones(1, 2, dtype=torch.int16)
z2 = torch.ones(1,2, dtype=torch.uint8)
print(z0.dtype)
print(z1.dtype)
print(z2.dtype)

torch.float32
torch.int32
torch.int64
torch.float32
torch.int16
torch.uint8


In [ ]:
x0 = torch.eye(3, dtype=torch.int64)
x1 = x0.float()
x2 = x0.double()
x3 = x0.to(torch.float32)
x4 = x0.to(torch.float64)
print(x0.dtype)
print(x1.dtype)
print(x2.dtype)
print(x3.dtype)
print(x4.dtype)

torch.int64
torch.float32
torch.float64
torch.float32
torch.float64


In [ ]:
x0 = torch.eye(3, dtype=torch.float64)
x1 = torch.zeros_like(x0)
x2 = x0.new_zeros(4,5)
x3 = torch.ones(6,7).to(x0)
print(x0.shape, x0.dtype)
print(x1.shape, x1.dtype)
print(x2.shape, x2.dtype)
print(x3.shape, x3.dtype)
print('x0 shape is %r, dtype is %r' % (x0, x0.dtype))

torch.Size([3, 3]) torch.float64
torch.Size([3, 3]) torch.float64
torch.Size([4, 5]) torch.float64
torch.Size([6, 7]) torch.float64
x0 shape is tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=torch.float64), dtype is torch.float64


In [ ]:
import torch
x = None
##############################################################################
# TODO: Make x contain a six-element vector of 64-bit floating-bit values,   #
# evenly spaced between 10 and 20.                                           #
##############################################################################
# Replace "pass" statement with your code
x = torch.tensor(list(range(10,22,2)), dtype=torch.float64)
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('x is a tensor: ', torch.is_tensor(x))
print('x has correct shape: ', x.shape == (6,))
print('x has correct dtype: ', x.dtype == torch.float64)
y = [10, 12, 14, 16, 18, 20]
correct_vals = all(a.item() == b for a, b in zip(x, y))
print('x has correct valus: ', correct_vals)

x is a tensor:  True
x has correct shape:  True
x has correct dtype:  True
x has correct valus:  True


In [ ]:
a = torch.tensor([0,11,22,33,42,55,66])
print(a[-4::2])

tensor([33, 55])


In [ ]:
import torch
a = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[1, :])
print(a[:2,-3:])
print(a[::2, 1:3])
row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1.shape)
print(row_r2.shape)
a = torch.tensor([[1,2,3,4],[5,6,7,8]])
b = a[0,1:]
c = a[0, 1:].clone()
print(a)
print(b)
print(c)
a[0,1]=20
b[1] = 30
c[2] = 40
print(a)
print(b)
print(c)
print(a.storage().data_ptr() == b.storage().data_ptr())

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([5, 6, 7, 8])
tensor([[2, 3, 4],
        [6, 7, 8]])
tensor([[ 2,  3],
        [10, 11]])
torch.Size([4])
torch.Size([1, 4])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([2, 3, 4])
tensor([2, 3, 4])
tensor([[ 1, 20, 30,  4],
        [ 5,  6,  7,  8]])
tensor([20, 30,  4])
tensor([ 2,  3, 40])
True


In [ ]:
# We will use this helper function to check your results
def check(orig, actual, expected):
  expected = torch.tensor(expected)
  same_elements = (actual == expected).all().item() == 1
  same_storage = (orig.storage().data_ptr() == actual.storage().data_ptr())
  return same_elements and same_storage

In [ ]:
# Create the following rank 2 tensor of shape (3, 5)
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]]
a = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

b, c, d, e = None, None, None, None
##############################################################################
# TODO: Extract the last row of a, and store it in b; it should have rank 1. #
##############################################################################
# Replace "pass" statement with your code
b = a[-1]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('b correct:', check(a, b, [11, 12, 13, 14, 15]))

##############################################################################
# TODO: Extract the third col of a, and store it in c; it should have rank 2 #
##############################################################################
# Replace "pass" statement with your code
c = a[:,2:3]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('c correct:', check(a, c, [[3], [8], [13]]))

##############################################################################
# TODO: Use slicing to extract the first two rows and first three columns    #
# from a; store the result into d.                                           #
##############################################################################
# Replace "pass" statement with your code
d = a[:2,:3]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('d correct:', check(a, d, [[1, 2, 3], [6, 7, 8]]))


##############################################################################
# TODO: Use slicing to extract a subtensor of a consisting of rows 0 and 2   #
# and columns 1 and 4.                                                       #
##############################################################################
# Replace "pass" statement with your code
e = a[::2, 1::3]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('e correct:', check(a, e, [[2, 5], [12, 15]]))

b correct: True
c correct: True
d correct: True
e correct: True


In [ ]:
a = torch.zeros(2, 4, dtype = torch.int64)
a[:, :2] = 1
a[:, 2:] = torch.tensor([[2,3],[4,5]])
print(a)

tensor([[1, 1, 2, 3],
        [1, 1, 4, 5]])


In [ ]:
x = torch.zeros(4, 6, dtype=torch.int64)
##############################################################################
# TODO: Use slicing to modify the tensor x so it has the following contents: #
#     [[1, 0, 2, 2, 2, 2],                                                   #
#      [0, 1, 2, 2, 2, 2],                                                   #
#      [3, 4, 3, 4, 5, 5],                                                   #
#      [3, 4, 3, 4, 5, 5]]                                                   #
# This can be achieved using five slicing assignment operations.             #
##############################################################################
# Replace "pass" statement with your code
x[:2,:2] = torch.eye(2)
x[:2,2:] = 2
x[2:,:4] = torch.tensor([[3,4,3,4],[3,4,3,4]])
x[2:,4:] = torch.ones(2) * 5
print(x)
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################

expected = [
    [1, 0, 2, 2, 2, 2],
    [0, 1, 2, 2, 2, 2],
    [3, 4, 3, 4, 5, 5],
    [3, 4, 3, 4, 5, 5],
]
print('correct:', x.tolist() == expected)

tensor([[1, 0, 2, 2, 2, 2],
        [0, 1, 2, 2, 2, 2],
        [3, 4, 3, 4, 5, 5],
        [3, 4, 3, 4, 5, 5]])
correct: True


In [ ]:
a = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
idx = [0,0,2,1,1]
print(a[idx])
idx = torch.tensor([3,2,1,0])
print(a[:,idx])
idx = [0,1,2]
print(a[idx,idx])
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
idx0 = torch.arange(a.shape[0])
idx1 = torch.tensor([1,2,1,0])
print(a[idx0, idx1])

tensor([[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 5,  6,  7,  8]])
tensor([[ 4,  3,  2,  1],
        [ 8,  7,  6,  5],
        [12, 11, 10,  9]])
tensor([ 1,  6, 11])
tensor([ 2,  6,  8, 10])


In [ ]:
# Build a tensor of shape (4, 3):
# [[ 1,  2,  3],
#  [ 4,  5,  6],
#  [ 7,  8,  9],
#  [10, 11, 12]]
a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print('Here is a:')
print(a)

b, c, d = None, None, None
##############################################################################
# TODO: Use integer array indexing to create a tensor of shape (4, 4) where: #
# - The first two columns are the same as the first column of a              #
# - The next column is the same as the third column of a                     #
# - The last column is the same as the second column of a                    #
# Store the resulting tensor in b.                                           #
##############################################################################
# Replace "pass" statement with your code
idx = [0,0,2,1]
b = a[:,idx]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('\nHere is b:')
print(b)
expected = [[1, 1, 3, 2], [4, 4, 6, 5], [7, 7, 9, 8], [10, 10, 12, 11]]
print('b correct:', b.tolist() == expected)

##############################################################################
# TODO: Use integer array indexing to create a new tensor which is the same  #
# as a, but has its rows reversed. Store the result in c.                    #
##############################################################################
# Replace "pass" statement with your code
idx = [3,2,1,0]
c = a[idx,:]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('\nHere is c:')
print(c)
expected = [[10, 11, 12], [7, 8, 9], [4, 5, 6], [1, 2, 3]]
print('c correct:', c.tolist() == expected)

##############################################################################
# TODO: Use integer array indexing to create a new tensor by selecting one   #
# element from each column of a:                                             #
# - From the first column, take the second element.                          #
# - From the second column, take the first element.                          #
# - From the third column, take the fourth element.                          #
# Store the result in d.                                                     #
##############################################################################
# Replace "pass" statement with your code
idx = [1,0,3]
idx1 = [0,1,2]
d = a[idx,idx1]
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('\nHere is d:')
print(d)
expected = [4, 2, 12]
print('d correct:', d.tolist() == expected)

Here is a:
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Here is b:
tensor([[ 1,  1,  3,  2],
        [ 4,  4,  6,  5],
        [ 7,  7,  9,  8],
        [10, 10, 12, 11]])
b correct: True

Here is c:
tensor([[10, 11, 12],
        [ 7,  8,  9],
        [ 4,  5,  6],
        [ 1,  2,  3]])
c correct: True

Here is d:
tensor([ 4,  2, 12])
d correct: True


In [ ]:
a = torch.tensor([[[1,2],[3,4]],[[1,5],[2,6]]])
mask = (a>3)
print(mask)
print(a[mask])

tensor([[[False, False],
         [False,  True]],

        [[False,  True],
         [False,  True]]])
tensor([4, 5, 6])


In [ ]:
def num_negative(x):
  """
  Return the number of negative values in the tensor x
 
  Inputs:
  - x: A tensor of any shape
 
  Returns:
  - num_neg: Number of negative values in x
  """
  num_neg = 0
  ##############################################################################
  # TODO: Use boolean masks to count the number of negative elements in x.     #
  ##############################################################################
  # Replace "pass" statement with your code
  x = x[x<0]
  num_neg = x.shape[0]

  ##############################################################################
  #                             END OF YOUR CODE                               #
  ##############################################################################
  return num_neg

# Make a few test cases
torch.manual_seed(598)
x0 = torch.tensor([[-1, -1, 0], [0, 1, 2], [3, 4, 5]])
x1 = torch.tensor([0, 1, 2, 3])
x2 = torch.randn(100, 100)
assert num_negative(x0) == 2
assert num_negative(x1) == 0
assert num_negative(x2) == 4984
print('num_negative seems to be correct!')

In [ ]:
def make_one_hot(x):
  """
  Construct a tensor of one-hot-vectors from a list of Python integers.

  Input:
  - x: A list of N ints

  Returns:
  - y: A tensor of shape (N, C) where C = 1 + max(x) is one more than the max
       value in x. The nth row of y is a one-hot-vector representation of x[n];
       In other words, if x[n] = c then y[n, c] = 1; all other elements of y are
       zeros.
  """
  y = None
  ##############################################################################
  # TODO: Complete the implementation of this function.                        #
  ##############################################################################
  # Replace "pass" statement with your code
  x = torch.tensor(x)
  y = torch.zeros(x.shape[0],max(x)+1)
  idx = torch.arange(x.shape[0])
  y[idx, x] = 1
  ##############################################################################
  #                             END OF YOUR CODE                               #
  ##############################################################################
  return y

In [ ]:
def check_one_hot(x, y):
  C = y.shape[1]
  for i, n in enumerate(x):
    if n >= C: return False
    for j in range(C):
      expected = 1.0 if j == n else 0.0
      if y[i, j].item() != expected: return False
  return True
      
x0 = [1, 4, 3, 2]
y0 = make_one_hot(x0)
print('Here is y0:')
print(y0)
assert check_one_hot(x0, y0), 'y0 is wrong'

x1 = [1, 3, 5, 7, 6, 2]
y1 = make_one_hot(x1)
print('\nHere is y1:')
print(y1)
assert check_one_hot(x1, y1), 'y1 is wrong'

print('all checks pass!')

Here is y0:
tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.]])

Here is y1:
tensor([[0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.]])
all checks pass!


In [ ]:
x0 = torch.tensor([[1,2,3,4],[5,6,7,8]])
x1 = x0.view(2,2,2,1)
x1[0][0][0][0] = 4
print(x0)
print(x1)
print(x0.view(2,-1))

tensor([[4, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[[[4],
          [2]],

         [[3],
          [4]]],


        [[[5],
          [6]],

         [[7],
          [8]]]])
tensor([[4, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
# We can reuse these functions for tensors of different shapes
def flatten(x):
  return x.view(-1)

def make_row_vec(x):
  return x.view(1, -1)

x0 = torch.tensor([[1, 2, 3], [4, 5, 6]])
x0_flat = flatten(x0)
x0_row = make_row_vec(x0)
print('x0:')
print(x0)
print('x0_flat:')
print(x0_flat)
print('x0_row:')
print(x0_row)

x1 = torch.tensor([[1, 2], [3, 4]])
x1_flat = flatten(x1)
x1_row = make_row_vec(x1)
print('\nx1:')
print(x1)
print('x1_flat:')
print(x1_flat)
print('x1_row:')
print(x1_row)

x0:
tensor([[1, 2, 3],
        [4, 5, 6]])
x0_flat:
tensor([1, 2, 3, 4, 5, 6])
x0_row:
tensor([[1, 2, 3, 4, 5, 6]])

x1:
tensor([[1, 2],
        [3, 4]])
x1_flat:
tensor([1, 2, 3, 4])
x1_row:
tensor([[1, 2, 3, 4]])


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_flat = x.view(-1)
print('x before modifying:')
print(x)
print('x_flat before modifying:')
print(x_flat)

x[0, 0] = 10   # x[0, 0] and x_flat[0] point to the same data
x_flat[1] = 20 # x_flat[1] and x[0, 1] point to the same data

print('\nx after modifying:')
print(x)
print('x_flat after modifying:')
print(x_flat)

x before modifying:
tensor([[1, 2, 3],
        [4, 5, 6]])
x_flat before modifying:
tensor([1, 2, 3, 4, 5, 6])

x after modifying:
tensor([[10, 20,  3],
        [ 4,  5,  6]])
x_flat after modifying:
tensor([10, 20,  3,  4,  5,  6])


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x.view(3,2))
x1 = x0.transpose(0,1)
print(x1)
x0 = torch.tensor([
        [[1,2,3,4],
         [5,6,7,8],
         [9,10,11,12]],
         [[13,14,15,16],
          [17,18,19,20],
          [21,22,23,24]]
])
print(x0.transpose(0,1))
x2 = x0.permute(1,2,0)
print(x2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]])
tensor([[[ 1,  2,  3,  4],
         [13, 14, 15, 16]],

        [[ 5,  6,  7,  8],
         [17, 18, 19, 20]],

        [[ 9, 10, 11, 12],
         [21, 22, 23, 24]]])
tensor([[[ 1, 13],
         [ 2, 14],
         [ 3, 15],
         [ 4, 16]],

        [[ 5, 17],
         [ 6, 18],
         [ 7, 19],
         [ 8, 20]],

        [[ 9, 21],
         [10, 22],
         [11, 23],
         [12, 24]]])


In [ ]:
x0 = torch.randn(2,3,4)
print(x0)

tensor([[[ 0.0918, -0.4222, -0.9922, -1.3039],
         [ 1.5098, -1.3650,  1.0543, -0.8688],
         [-1.0850,  0.3146,  0.6160, -0.2579]],

        [[ 0.5059, -0.3665,  0.0207,  0.9410],
         [ 2.0738,  1.6595,  0.4608, -0.6292],
         [-1.0665,  1.6111,  0.1605,  1.1943]]])


In [ ]:
x0 = torch.randn(2, 3, 4)

try:
  # This sequence of reshape operations will crash
  x1 = x0.transpose(1, 2).view(8, 3)
except RuntimeError as e:
  print(type(e), e)
  
# We can solve the problem using either .contiguous() or .reshape()
x1 = x0.transpose(1, 2).contiguous().view(8, 3)
x2 = x0.transpose(1, 2).reshape(8, 3)
print('x1 shape: ', x1.shape)
print('x2 shape: ', x2.shape)

<class 'RuntimeError'> view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
x1 shape:  torch.Size([8, 3])
x2 shape:  torch.Size([8, 3])


In [ ]:
x0 = torch.arange(24)
print('Here is x0:')
print(x0)

x1 = None
##############################################################################
# TODO: Use reshape operations to create x1 from x0                          #
##############################################################################
# Replace "pass" statement with your code
x1 = x0.view(2,3,4)
x1 = x1.permute(1,0,2).reshape(3,8)
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('\nHere is x1:')
print(x1)

expected = [
    [0, 1,  2,  3, 12, 13, 14, 15],
    [4, 5,  6,  7, 16, 17, 18, 19],
    [8, 9, 10, 11, 20, 21, 22, 23]]
print('Correct:', x1.tolist() == expected)

Here is x0:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

Here is x1:
tensor([[ 0,  1,  2,  3, 12, 13, 14, 15],
        [ 4,  5,  6,  7, 16, 17, 18, 19],
        [ 8,  9, 10, 11, 20, 21, 22, 23]])
Correct: True


In [ ]:
x = torch.tensor([[1,2,3,4]], dtype = torch.float32)
y = torch.tensor([[5,6,7,8]], dtype=torch.float32)
print(x*y)
print(torch.mul(x,y))
print(x.mul(y))
print(x.sqrt())
print(torch.cos(x))

tensor([[ 5., 12., 21., 32.]])
tensor([[ 5., 12., 21., 32.]])
tensor([[ 5., 12., 21., 32.]])
tensor([[1.0000, 1.4142, 1.7321, 2.0000]])
tensor([[ 0.5403, -0.4161, -0.9900, -0.6536]])


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
print(torch.sum(x))
print(x.sum())
print(torch.sum(x, dim=1))
print(x.sum(dim=0))

tensor(21.)
tensor(21.)
tensor([ 6., 15.])
tensor([5., 7., 9.])


In [ ]:
x = torch.tensor([[2,4,3,5],[3,3,5,2]], dtype = torch.float32)
a= x.mean(dim=1)
print(a)

tensor([3.5000, 3.2500])


In [ ]:
x = torch.randn(128,10,3,64,64)
x = x.mean(dim=1)
x = x.sum(dim=2)
x = x.mean(dim=1, keepdim=True)

In [ ]:
def zero_row_min(x):
  """
  Return a copy of x, where the minimum value along each row has been set to 0.

  For example, if x is:
  x = torch.tensor([[
        [10, 20, 30],
        [ 2,  5,  1]
      ]])
  
  Then y = zero_row_min(x) should be:
  torch.tensor([
    [0, 20, 30],
    [2,  5,  0]
  ])

  Inputs:
  - x: Tensor of rank 2 with shape (N, M)

  Returns:
  - y: Tensor of rank 2 that is a copy of x, except the minimum value along each
       row is replaced with 0.
  """
  y = x.clone()
  ##############################################################################
  # TODO: Complete the implementation of this function.                        #
  ##############################################################################
  # Replace "pass" statement with your code
  a, b = x.min(dim=1)
  idx = torch.arange(x.shape[0])
  y[idx, b] = 0
   ##############################################################################
  #                             END OF YOUR CODE                               #
  ##############################################################################
  return y

In [ ]:
x0 = torch.tensor([[10, 20, 30], [2, 5, 1]])
print('Here is x0:')
print(x0)
y0 = zero_row_min(x0)
print('Here is y0:')
print(y0)
assert y0.tolist() == [[0, 20, 30], [2, 5, 0]]

x1 = torch.tensor([[2, 5, 10, -1], [1, 3, 2, 4], [5, 6, 2, 10]])
print('\nHere is x1:')
print(x1)
y1 = zero_row_min(x1)
print('Here is y1:')
print(y1)
assert y1.tolist() == [[2, 5, 10, 0], [0, 3, 2, 4], [5, 6, 0, 10]]

print('\nSimple tests pass!')

Here is x0:
tensor([[10, 20, 30],
        [ 2,  5,  1]])
Here is y0:
tensor([[ 0, 20, 30],
        [ 2,  5,  0]])

Here is x1:
tensor([[ 2,  5, 10, -1],
        [ 1,  3,  2,  4],
        [ 5,  6,  2, 10]])
Here is y1:
tensor([[ 2,  5, 10,  0],
        [ 0,  3,  2,  4],
        [ 5,  6,  0, 10]])

Simple tests pass!


In [ ]:
v = torch.tensor([9,10], dtype=torch.float32)
w = torch.tensor([11, 12], dtype=torch.float32)
x = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
y = torch.tensor([[5,6],[7,8]], dtype=torch.float32)
print(x.matmul(v))

tensor([29., 67.])


In [ ]:
B, N, M, P = 3, 2, 5, 4
x = torch.rand(B, N, M)  # Random tensor of shape (B, N, M)
y = torch.rand(B, M, P)  # Random tensor of shape (B, M, P)

# We can use a for loop to (inefficiently) compute a batch of matrix multiply
# operations
z1 = torch.empty(B, N, P)  # Empty tensor of shape (B, N, P)
for i in range(B):
  z1[i] = x[i].mm(y[i])
print('Here is the result of batched matrix multiply with a loop:')
print(z1)

z2 = None
##############################################################################
# TODO: Use bmm to compute a batched matrix multiply between x and y; store  #
# the result in z2.                                                          #
##############################################################################
# Replace "pass" statement with your code
z2 =torch.bmm(x,y)
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
print('\nHere is the result of batched matrix multiply with bmm:')
print(z2)

# The two may not return exactly the same result; different linear algebra
# routines often return slightly different results due to the fact that
# floating-point math is non-exact and non-associative.
diff = (z1 - z2).abs().max().item()
print('\nDifference:', diff)
print('Difference within threshold:', diff < 1e-6)

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = torch.tensor([1,0,1])
y = torch.zeros_like(x)

for i in range(4):
    y[i,:] = x[i,:] + v
print(y)

vv = v.repeat((4,2))
print(vv)

print(x + v)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])
tensor([[1, 0, 1, 1, 0, 1],
        [1, 0, 1, 1, 0, 1],
        [1, 0, 1, 1, 0, 1],
        [1, 0, 1, 1, 0, 1]])
tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


In [ ]:
v = torch.tensor([1,2,3])
w = torch.tensor([4,5])
print(v.view(3,1)*w)

tensor([[ 4,  5],
        [ 8, 10],
        [12, 15]])


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])  # x has shape (2, 3)
v = torch.tensor([1, 2, 3])               # v has shape (3,)
print('Here is the matrix:')
print(x)
print('\nHere is the vector:')
print(v)

# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
print('\nAdd the vector to each row of the matrix:')
print(x + v)

Here is the matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])

Here is the vector:
tensor([1, 2, 3])

Add the vector to each row of the matrix:
tensor([[2, 4, 6],
        [5, 7, 9]])


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
w = torch.tensor([4,5])
print(w.view(-1))

tensor([4, 5])


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
c = torch.tensor([1,10,11,100])
y = c. view(-1,1,1) * x
print(y)

tensor([[[  1,   2,   3],
         [  4,   5,   6]],

        [[ 10,  20,  30],
         [ 40,  50,  60]],

        [[ 11,  22,  33],
         [ 44,  55,  66]],

        [[100, 200, 300],
         [400, 500, 600]]])


In [ ]:
def normalize_columns(x):
  """
  Normalize the columns of a matrix by subtracting the mean and dividing by the
  standard deviation.
 
  Inputs:
  - x: Tensor of shape (N, M)
  
  Returns:
  - y: Tensor of shape (N, M) which is a copy of x with normalized columns.
  """
  y = x.clone()
  ##############################################################################
  # TODO: Complete the implementation of this function. Do not modify x.       #
  # Your implementation should not use any loops; instead you should use       #
  # reduction and broadcasting operations.                                     #
  ##############################################################################
  # Replace "pass" statement with your code
  y = y.t()
  m = y.mean(dim=1).view(3,1)
  w = y.std(dim=1).view(3,1)
  y = ((y-m)/w)
  y = y.t()
  ##############################################################################
  #                             END OF YOUR CODE                               #
  ##############################################################################
  return y

In [ ]:
x0 = torch.tensor([[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]])
y0 = normalize_columns(x0)
print('Here is x0:')
print(x0)
print('Here is y0:')
print(y0)
assert y0.tolist() == [[0., 1., 1.], [1., -1., -1.], [-1., 0., 0.]]
assert x0.tolist() == [[0., 30., 600.], [1., 10., 200.], [-1., 20., 400.]]

Here is x0:
tensor([[  0.,  30., 600.],
        [  1.,  10., 200.],
        [ -1.,  20., 400.]])
Here is y0:
tensor([[ 0.,  1.,  1.],
        [ 1., -1., -1.],
        [-1.,  0.,  0.]])


In [ ]:
import torch

if torch.cuda.is_available:
    print('pytorch can use gpu')
else:
    print('pytorch annot use gpu')

pytorch can use gpu


In [ ]:
x0 = torch.tensor([[1,2],[3,4]], dtype = torch.float32)
print(x0.device)
x1 = x0.to('cuda')
print(x1.device)
x2 = x0.cuda()
print(x2.device)
x3 = x2.to('cpu')
print(x3.device)
x4 = x2.cpu()
print(x4.device)
y = torch.tensor([[1,2,3],[4,5,6]],dtype = torch.float64, device='cuda')
print(y.device, y.dtype)
x5 = x0.to(y)
print(x5.device, x5.dtype)

cpu
cuda:0
cuda:0
cpu
cpu
cuda:0 torch.float64
cuda:0 torch.float64


In [ ]:
import time
a_cpu = torch.randn(10000,10000,dtype=torch.float32)
b_cpu = torch.randn(10000,10000,dtype=torch.float32)

a_gpu = a_cpu.cuda()
b_gpu = b_cpu.cuda()
torch.cuda.synchronize()

t0 = time.time()
c_cpu = a_cpu + b_cpu
t1 = time.time()
c_gpu = a_gpu + b_gpu
torch.cuda.synchronize()
t2 = time.time()

cpu_time = 1000.0 * (t1 - t0)
gpu_time = 1000.0 * (t2 - t1)
print(cpu_time)
print(gpu_time)

diff = (c_gpu.cpu() - c_cpu).abs().max().item()
print('Max difference between c_gpu and c_cpu:', diff)


130.74207305908203
8.459806442260742
Max difference between c_gpu and c_cpu: 0.0


In [ ]:
a = torch.tensor([[1,2],[3,4]])
print(a.max().item())

4


In [ ]:
import time

x = torch.rand(512, 4096)
w = torch.rand(4096, 4096)

t0 = time.time()
y0 = x.mm(w)
t1 = time.time()

y1 = None
##############################################################################
# TODO: Write a bit of code that performs matrix multiplication of x and w   #
# on the GPU, and then moves the result back to the CPU. Store the result    #
# in y1.
##############################################################################
# Replace "pass" statement with your code
x = x.cuda()
w = w.cuda()
y1 = x.mm(w).to('cpu')
##############################################################################
#                             END OF YOUR CODE                               #
##############################################################################
torch.cuda.synchronize()
t2 = time.time()

print('y1 on CPU:', y1.device == torch.device('cpu'))
diff = (y0 - y1).abs().max().item()
print('Max difference between y0 and y1:', diff)
print('Difference within tolerance:', diff < 5e-2)

cpu_time = 1000.0 * (t1 - t0)
gpu_time = 1000.0 * (t2 - t1)
print('CPU time: %.2f ms' % cpu_time)
print('GPU time: %.2f ms' % gpu_time)
print('GPU speedup: %.2f x' % (cpu_time / gpu_time))

y1 on CPU: True
Max difference between y0 and y1: 0.0045166015625
Difference within tolerance: True
CPU time: 227.42 ms
GPU time: 25.18 ms
GPU speedup: 9.03 x


In [ ]:
x1 = torch.tensor([1,2,3])
x2 = x1.to('cpu')
x2[0] = 10
print(x1,x2)

tensor([10,  2,  3]) tensor([10,  2,  3])
